version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - compose install
  build:
    commands:
      - php artisan key:generate
      - phpunit
  post_build:
    commands:
      - echo Build completed on `date`
